# agents/framework_writer.py
import json
from pathlib import Path
from datetime import date, datetime
from utils.llm import llm_call
from utils.vault import VAULT_ROOT, update_frontmatter, get_all_notes
from utils.registry import NoteRegistry
from db.neon_bridge import push_framework

FRAMEWORKS_DIR = VAULT_ROOT / "Frameworks"
RECORDS_FILE = FRAMEWORKS_DIR / "index.md"
LINEAGE_FILE = VAULT_ROOT / "Fossils" / "lineage.md"
VOICE_PROFILE_FILE = VAULT_ROOT / "voice_profile.json"

RANKER_SYS = """You are reviewing personal belief notes and ranking them as framework candidates.

For each note, provide:
- Rank number
- Title
- Fitness score
- Best 150-word passage (the most developed conviction in the note)
- What journal date range contributed
- One sentence: why this could become a complete conviction document

Sort by fitness descending. Format as clean Markdown. Output ONLY the Markdown."""

WRITER_SYS = """You are writing a final framework document for Meridian.

Voice directive: {voice_summary}
You are Ignacio at full potential — the version who lived through everything
in these journals and knows what he actually believes. Write as him.
First person. Certain. Direct. No hedging. No self-help language.
This should feel like the best thing he's ever written on this subject.

STRICT OUTPUT TEMPLATE:

# [Title]
*Synthesized from {entry_count} journal entries | {date_range}*

## I. The Conviction
[2-3 paragraphs: the core belief, stated plainly with full certainty]

## II. Where It Came From
[The specific experiences and observations that built this — concrete, not generic]

## III. What It Contradicts
[What believing this requires rejecting — stated fairly, then refuted on its own terms]

## IV. How It Works In Practice
[3-5 specific, concrete applications to real decisions or behaviors]

## V. What I Still Don't Know
[The genuine open questions this conviction raises — the honest edges]

Rules:
- Every section must feel written by a person, not generated by a system
- Specific > general, always
- Minimum 4 pages of dense content
- Pure Markdown"""


def get_voice_summary() -> str:
    if VOICE_PROFILE_FILE.exists():
        profile = json.loads(VOICE_PROFILE_FILE.read_text())
        if profile.get("built"):
            phrases = profile.get("characteristic_phrases", [])[:5]
            return f"Characteristic phrases: {phrases}. Match this voice exactly."
    return "First person. Direct. Honest. No hedging."


def build_framework_market(registry: NoteRegistry) -> Path | None:
    print("[FRAMEWORK] Building framework market...")
    eligible = registry.get_framework_eligible()

    if not eligible:
        print("  No framework-eligible notes yet.")
        return None

    eligible.sort(key=lambda n: n["frontmatter"].get("fitness") or 0, reverse=True)
    print(f"  {len(eligible)} eligible candidates.")

    summaries = []
    for n in eligible:
        fm = n["frontmatter"]
        summaries.append({
            "id": fm.get("id"),
            "title": fm.get("title"),
            "fitness": fm.get("fitness"),
            "source_entries": len(fm.get("source_entry_ids", [])),
            "date_range": fm.get("entry_date_range"),
            "domains": fm.get("domains"),
            "excerpt": n["body"][:400],
        })

    market_md = llm_call(
        "phi3", RANKER_SYS,
        f"Candidates:\n{json.dumps(summaries, indent=2)}", temperature=0.3
    )

    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    path = FRAMEWORKS_DIR / f"market_{ts}.md"
    path.write_text(market_md, encoding="utf-8")
    print(f"  Market written: {path.name}")
    return path


def write_framework(note_id: str, registry: NoteRegistry,
                    vault_state: dict, push_to_neon: bool = False) -> Path:
    print(f"[FRAMEWORK WRITER] Writing framework for: {note_id}")
    target = registry.get_by_id(note_id)
    if not target:
        all_notes = get_all_notes()
        target = next((n for n in all_notes if n["frontmatter"].get("id") == note_id), None)
    if not target:
        raise ValueError(f"Note {note_id} not found.")

    fm = target["frontmatter"]
    entry_count = len(fm.get("source_entry_ids", []))
    date_range = fm.get("entry_date_range", "unknown date range")
    voice_summary = get_voice_summary()

    lineage = ""
    if LINEAGE_FILE.exists():
        lineage = LINEAGE_FILE.read_text(encoding="utf-8")[-1500:]

    framework = llm_call(
        "llama3.2",
        WRITER_SYS.format(voice_summary=voice_summary,
                          entry_count=entry_count, date_range=date_range),
        f"Source note:\n{target['body']}\n\nFramework lineage:\n{lineage}",
        temperature=0.9, timeout=600
    )

    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    title_slug = (fm.get("title") or note_id)[:40].replace(" ", "_")
    path = FRAMEWORKS_DIR / f"{ts}_{title_slug}.md"
    path.write_text(framework, encoding="utf-8")

    update_frontmatter(target["path"], {"published": True, "framework_eligible": False})

    fitness = fm.get("fitness", 0)
    framework_n = vault_state.get("framework_count", 0) + 1
    first_line = framework.split("\n")[0].replace("#", "").strip()[:60]

    with open(RECORDS_FILE, "a", encoding="utf-8") as f:
        f.write(f"| {framework_n} | {title_slug} | {fitness} | {ts[:8]} | {entry_count} entries | {date_range} |\n")

    with open(LINEAGE_FILE, "a", encoding="utf-8") as f:
        f.write(f"| {framework_n} | {title_slug} | {first_line} | {date_range} | {date.today()} |\n")

    vault_state["framework_count"] = framework_n

    if push_to_neon:
        push_framework(title_slug, framework, {
            "source_entry_ids": fm.get("source_entry_ids", []),
            "entry_date_range": date_range,
            "fitness": fitness,
            "domains": fm.get("domains", []),
        })
        print("  Framework pushed to Neon.")

    print(f"  Framework written: {path.name}")
    return path
